<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['nama_indonesia' => 'Afganistan', 'nama_inggris' => 'Afghanistan', 'kode_iso' => 'AF', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Afrika Selatan', 'nama_inggris' => 'South Africa', 'kode_iso' => 'ZA', 'benua' => 'Africa', 'subbenua' => 'Southern Africa'],
            ['nama_indonesia' => 'Afrika Tengah', 'nama_inggris' => 'Central African Republic', 'kode_iso' => 'CF', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Albania', 'nama_inggris' => 'Albania', 'kode_iso' => 'AL', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Aljazair', 'nama_inggris' => 'Algeria', 'kode_iso' => 'DZ', 'benua' => 'Africa', 'subbenua' => 'Northern Africa'],
            ['nama_indonesia' => 'Amerika Serikat', 'nama_inggris' => 'United States', 'kode_iso' => 'US', 'benua' => 'North America', 'subbenua' => 'Northern America'],
            ['nama_indonesia' => 'Andorra', 'nama_inggris' => 'Andorra', 'kode_iso' => 'AD', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Angola', 'nama_inggris' => 'Angola', 'kode_iso' => 'AO', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Antigua dan Barbuda', 'nama_inggris' => 'Antigua and Barbuda', 'kode_iso' => 'AG', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Arab Saudi', 'nama_inggris' => 'Saudi Arabia', 'kode_iso' => 'SA', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Argentina', 'nama_inggris' => 'Argentina', 'kode_iso' => 'AR', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Armenia', 'nama_inggris' => 'Armenia', 'kode_iso' => 'AM', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Australia', 'nama_inggris' => 'Australia', 'kode_iso' => 'AU', 'benua' => 'Oceania', 'subbenua' => 'Australia and New Zealand'],
            ['nama_indonesia' => 'Austria', 'nama_inggris' => 'Austria', 'kode_iso' => 'AT', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Azerbaijan', 'nama_inggris' => 'Azerbaijan', 'kode_iso' => 'AZ', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Bahama', 'nama_inggris' => 'Bahamas', 'kode_iso' => 'BS', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Bahrain', 'nama_inggris' => 'Bahrain', 'kode_iso' => 'BH', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Bangladesh', 'nama_inggris' => 'Bangladesh', 'kode_iso' => 'BD', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Barbados', 'nama_inggris' => 'Barbados', 'kode_iso' => 'BB', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Belanda', 'nama_inggris' => 'Netherlands', 'kode_iso' => 'NL', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Belarus', 'nama_inggris' => 'Belarus', 'kode_iso' => 'BY', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Belgia', 'nama_inggris' => 'Belgium', 'kode_iso' => 'BE', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Belize', 'nama_inggris' => 'Belize', 'kode_iso' => 'BZ', 'benua' => 'North America', 'subbenua' => 'Central America'],
            ['nama_indonesia' => 'Benin', 'nama_inggris' => 'Benin', 'kode_iso' => 'BJ', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Bhutan', 'nama_inggris' => 'Bhutan', 'kode_iso' => 'BT', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Bolivia', 'nama_inggris' => 'Bolivia', 'kode_iso' => 'BO', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Bosnia dan Herzegovina', 'nama_inggris' => 'Bosnia and Herzegovina', 'kode_iso' => 'BA', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Botswana', 'nama_inggris' => 'Botswana', 'kode_iso' => 'BW', 'benua' => 'Africa', 'subbenua' => 'Southern Africa'],
            ['nama_indonesia' => 'Brasil', 'nama_inggris' => 'Brazil', 'kode_iso' => 'BR', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Britania Raya', 'nama_inggris' => 'United Kingdom', 'kode_iso' => 'GB', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Brunei Darussalam', 'nama_inggris' => 'Brunei Darussalam', 'kode_iso' => 'BN', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Bulgaria', 'nama_inggris' => 'Bulgaria', 'kode_iso' => 'BG', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Burkina Faso', 'nama_inggris' => 'Burkina Faso', 'kode_iso' => 'BF', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Burundi', 'nama_inggris' => 'Burundi', 'kode_iso' => 'BI', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Ceko', 'nama_inggris' => 'Czechia', 'kode_iso' => 'CZ', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Chad', 'nama_inggris' => 'Chad', 'kode_iso' => 'TD', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Cile', 'nama_inggris' => 'Chile', 'kode_iso' => 'CL', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Côte d\'Ivoire (Pantai Gading)', 'nama_inggris' => 'Côte d\'Ivoire', 'kode_iso' => 'CI', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Denmark', 'nama_inggris' => 'Denmark', 'kode_iso' => 'DK', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Djibouti', 'nama_inggris' => 'Djibouti', 'kode_iso' => 'DJ', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Dominika', 'nama_inggris' => 'Dominica', 'kode_iso' => 'DM', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Ekuador', 'nama_inggris' => 'Ecuador', 'kode_iso' => 'EC', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'El Salvador', 'nama_inggris' => 'El Salvador', 'kode_iso' => 'SV', 'benua' => 'North America', 'subbenua' => 'Central America'],
            ['nama_indonesia' => 'Eritrea', 'nama_inggris' => 'Eritrea', 'kode_iso' => 'ER', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Estonia', 'nama_inggris' => 'Estonia', 'kode_iso' => 'EE', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Eswatini', 'nama_inggris' => 'Eswatini', 'kode_iso' => 'SZ', 'benua' => 'Africa', 'subbenua' => 'Southern Africa'],
            ['nama_indonesia' => 'Etiopia', 'nama_inggris' => 'Ethiopia', 'kode_iso' => 'ET', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Fiji', 'nama_inggris' => 'Fiji', 'kode_iso' => 'FJ', 'benua' => 'Oceania', 'subbenua' => 'Melanesia'],
            ['nama_indonesia' => 'Filipina', 'nama_inggris' => 'Philippines', 'kode_iso' => 'PH', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Finlandia', 'nama_inggris' => 'Finland', 'kode_iso' => 'FI', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Gabon', 'nama_inggris' => 'Gabon', 'kode_iso' => 'GA', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Gambia', 'nama_inggris' => 'Gambia', 'kode_iso' => 'GM', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Georgia', 'nama_inggris' => 'Georgia', 'kode_iso' => 'GE', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Ghana', 'nama_inggris' => 'Ghana', 'kode_iso' => 'GH', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Grenada', 'nama_inggris' => 'Grenada', 'kode_iso' => 'GD', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Guatemala', 'nama_inggris' => 'Guatemala', 'kode_iso' => 'GT', 'benua' => 'North America', 'subbenua' => 'Central America'],
            ['nama_indonesia' => 'Guinea', 'nama_inggris' => 'Guinea', 'kode_iso' => 'GN', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Guinea Khatulistiwa', 'nama_inggris' => 'Equatorial Guinea', 'kode_iso' => 'GQ', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Guinea-Bissau', 'nama_inggris' => 'Guinea-Bissau', 'kode_iso' => 'GW', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Guyana', 'nama_inggris' => 'Guyana', 'kode_iso' => 'GY', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Haiti', 'nama_inggris' => 'Haiti', 'kode_iso' => 'HT', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Honduras', 'nama_inggris' => 'Honduras', 'kode_iso' => 'HN', 'benua' => 'North America', 'subbenua' => 'Central America'],
            ['nama_indonesia' => 'Hongaria', 'nama_inggris' => 'Hungary', 'kode_iso' => 'HU', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'India', 'nama_inggris' => 'India', 'kode_iso' => 'IN', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Indonesia', 'nama_inggris' => 'Indonesia', 'kode_iso' => 'ID', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Irak', 'nama_inggris' => 'Iraq', 'kode_iso' => 'IQ', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Iran', 'nama_inggris' => 'Iran', 'kode_iso' => 'IR', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Irlandia', 'nama_inggris' => 'Ireland', 'kode_iso' => 'IE', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Islandia', 'nama_inggris' => 'Iceland', 'kode_iso' => 'IS', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Israel', 'nama_inggris' => 'Israel', 'kode_iso' => 'IL', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Italia', 'nama_inggris' => 'Italy', 'kode_iso' => 'IT', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Jamaika', 'nama_inggris' => 'Jamaica', 'kode_iso' => 'JM', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Jepang', 'nama_inggris' => 'Japan', 'kode_iso' => 'JP', 'benua' => 'Asia', 'subbenua' => 'Eastern Asia'],
            ['nama_indonesia' => 'Jerman', 'nama_inggris' => 'Germany', 'kode_iso' => 'DE', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Kamboja', 'nama_inggris' => 'Cambodia', 'kode_iso' => 'KH', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Kamerun', 'nama_inggris' => 'Cameroon', 'kode_iso' => 'CM', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Kanada', 'nama_inggris' => 'Canada', 'kode_iso' => 'CA', 'benua' => 'North America', 'subbenua' => 'Northern America'],
            ['nama_indonesia' => 'Kazakhstan', 'nama_inggris' => 'Kazakhstan', 'kode_iso' => 'KZ', 'benua' => 'Asia', 'subbenua' => 'Central Asia'],
            ['nama_indonesia' => 'Kenya', 'nama_inggris' => 'Kenya', 'kode_iso' => 'KE', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Kirgizstan', 'nama_inggris' => 'Kyrgyzstan', 'kode_iso' => 'KG', 'benua' => 'Asia', 'subbenua' => 'Central Asia'],
            ['nama_indonesia' => 'Kiribati', 'nama_inggris' => 'Kiribati', 'kode_iso' => 'KI', 'benua' => 'Oceania', 'subbenua' => 'Micronesia'],
            ['nama_indonesia' => 'Kolombia', 'nama_inggris' => 'Colombia', 'kode_iso' => 'CO', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Komoro', 'nama_inggris' => 'Comoros', 'kode_iso' => 'KM', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Kongo', 'nama_inggris' => 'Congo', 'kode_iso' => 'CG', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Kongo, Republik Demokratik', 'nama_inggris' => 'Congo, Democratic Republic of the', 'kode_iso' => 'CD', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Korea Selatan', 'nama_inggris' => 'South Korea', 'kode_iso' => 'KR', 'benua' => 'Asia', 'subbenua' => 'Eastern Asia'],
            ['nama_indonesia' => 'Korea Utara', 'nama_inggris' => 'North Korea', 'kode_iso' => 'KP', 'benua' => 'Asia', 'subbenua' => 'Eastern Asia'],
            ['nama_indonesia' => 'Kosta Rika', 'nama_inggris' => 'Costa Rica', 'kode_iso' => 'CR', 'benua' => 'North America', 'subbenua' => 'Central America'],
            ['nama_indonesia' => 'Kroasia', 'nama_inggris' => 'Croatia', 'kode_iso' => 'HR', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Kuba', 'nama_inggris' => 'Cuba', 'kode_iso' => 'CU', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Kuwait', 'nama_inggris' => 'Kuwait', 'kode_iso' => 'KW', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Laos', 'nama_inggris' => 'Lao People\'s Democratic Republic', 'kode_iso' => 'LA', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Latvia', 'nama_inggris' => 'Latvia', 'kode_iso' => 'LV', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Lebanon', 'nama_inggris' => 'Lebanon', 'kode_iso' => 'LB', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Lesotho', 'nama_inggris' => 'Lesotho', 'kode_iso' => 'LS', 'benua' => 'Africa', 'subbenua' => 'Southern Africa'],
            ['nama_indonesia' => 'Liberia', 'nama_inggris' => 'Liberia', 'kode_iso' => 'LR', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Libya', 'nama_inggris' => 'Libya', 'kode_iso' => 'LY', 'benua' => 'Africa', 'subbenua' => 'Northern Africa'],
            ['nama_indonesia' => 'Liechtenstein', 'nama_inggris' => 'Liechtenstein', 'kode_iso' => 'LI', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Lituania', 'nama_inggris' => 'Lithuania', 'kode_iso' => 'LT', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Luksemburg', 'nama_inggris' => 'Luxembourg', 'kode_iso' => 'LU', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Madagaskar', 'nama_inggris' => 'Madagascar', 'kode_iso' => 'MG', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Makedonia Utara', 'nama_inggris' => 'North Macedonia', 'kode_iso' => 'MK', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Maladewa', 'nama_inggris' => 'Maldives', 'kode_iso' => 'MV', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Malawi', 'nama_inggris' => 'Malawi', 'kode_iso' => 'MW', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Malaysia', 'nama_inggris' => 'Malaysia', 'kode_iso' => 'MY', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Mali', 'nama_inggris' => 'Mali', 'kode_iso' => 'ML', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Malta', 'nama_inggris' => 'Malta', 'kode_iso' => 'MT', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Maroko', 'nama_inggris' => 'Morocco', 'kode_iso' => 'MA', 'benua' => 'Africa', 'subbenua' => 'Northern Africa'],
            ['nama_indonesia' => 'Marshall, Kepulauan', 'nama_inggris' => 'Marshall Islands', 'kode_iso' => 'MH', 'benua' => 'Oceania', 'subbenua' => 'Micronesia'],
            ['nama_indonesia' => 'Mauritania', 'nama_inggris' => 'Mauritania', 'kode_iso' => 'MR', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Mauritius', 'nama_inggris' => 'Mauritius', 'kode_iso' => 'MU', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Meksiko', 'nama_inggris' => 'Mexico', 'kode_iso' => 'MX', 'benua' => 'North America', 'subbenua' => 'Northern America'],
            ['nama_indonesia' => 'Mesir', 'nama_inggris' => 'Egypt', 'kode_iso' => 'EG', 'benua' => 'Africa', 'subbenua' => 'Northern Africa'],
            ['nama_indonesia' => 'Mikronesia', 'nama_inggris' => 'Micronesia', 'kode_iso' => 'FM', 'benua' => 'Oceania', 'subbenua' => 'Micronesia'],
            ['nama_indonesia' => 'Moldova', 'nama_inggris' => 'Moldova', 'kode_iso' => 'MD', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Monako', 'nama_inggris' => 'Monaco', 'kode_iso' => 'MC', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Mongolia', 'nama_inggris' => 'Mongolia', 'kode_iso' => 'MN', 'benua' => 'Asia', 'subbenua' => 'Eastern Asia'],
            ['nama_indonesia' => 'Montenegro', 'nama_inggris' => 'Montenegro', 'kode_iso' => 'ME', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Mozambik', 'nama_inggris' => 'Mozambique', 'kode_iso' => 'MZ', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Myanmar', 'nama_inggris' => 'Myanmar', 'kode_iso' => 'MM', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Namibia', 'nama_inggris' => 'Namibia', 'kode_iso' => 'NA', 'benua' => 'Africa', 'subbenua' => 'Southern Africa'],
            ['nama_indonesia' => 'Nauru', 'nama_inggris' => 'Nauru', 'kode_iso' => 'NR', 'benua' => 'Oceania', 'subbenua' => 'Micronesia'],
            ['nama_indonesia' => 'Nepal', 'nama_inggris' => 'Nepal', 'kode_iso' => 'NP', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Niger', 'nama_inggris' => 'Niger', 'kode_iso' => 'NE', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Nigeria', 'nama_inggris' => 'Nigeria', 'kode_iso' => 'NG', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Nikaragua', 'nama_inggris' => 'Nicaragua', 'kode_iso' => 'NI', 'benua' => 'North America', 'subbenua' => 'Central America'],
            ['nama_indonesia' => 'Norwegia', 'nama_inggris' => 'Norway', 'kode_iso' => 'NO', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Oman', 'nama_inggris' => 'Oman', 'kode_iso' => 'OM', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Pakistan', 'nama_inggris' => 'Pakistan', 'kode_iso' => 'PK', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Palau', 'nama_inggris' => 'Palau', 'kode_iso' => 'PW', 'benua' => 'Oceania', 'subbenua' => 'Micronesia'],
            ['nama_indonesia' => 'Palestina', 'nama_inggris' => 'Palestine, State of', 'kode_iso' => 'PS', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Panama', 'nama_inggris' => 'Panama', 'kode_iso' => 'PA', 'benua' => 'North America', 'subbenua' => 'Central America'],
            ['nama_indonesia' => 'Papua Nugini', 'nama_inggris' => 'Papua New Guinea', 'kode_iso' => 'PG', 'benua' => 'Oceania', 'subbenua' => 'Melanesia'],
            ['nama_indonesia' => 'Paraguay', 'nama_inggris' => 'Paraguay', 'kode_iso' => 'PY', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Prancis', 'nama_inggris' => 'France', 'kode_iso' => 'FR', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Peru', 'nama_inggris' => 'Peru', 'kode_iso' => 'PE', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Polandia', 'nama_inggris' => 'Poland', 'kode_iso' => 'PL', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Portugal', 'nama_inggris' => 'Portugal', 'kode_iso' => 'PT', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Qatar', 'nama_inggris' => 'Qatar', 'kode_iso' => 'QA', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Republik Dominika', 'nama_inggris' => 'Dominican Republic', 'kode_iso' => 'DO', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Rumania', 'nama_inggris' => 'Romania', 'kode_iso' => 'RO', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Rusia', 'nama_inggris' => 'Russian Federation', 'kode_iso' => 'RU', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Rwanda', 'nama_inggris' => 'Rwanda', 'kode_iso' => 'RW', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Saint Kitts dan Nevis', 'nama_inggris' => 'Saint Kitts and Nevis', 'kode_iso' => 'KN', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Saint Lucia', 'nama_inggris' => 'Saint Lucia', 'kode_iso' => 'LC', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Saint Vincent dan Grenadines', 'nama_inggris' => 'Saint Vincent and the Grenadines', 'kode_iso' => 'VC', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Samoa', 'nama_inggris' => 'Samoa', 'kode_iso' => 'WS', 'benua' => 'Oceania', 'subbenua' => 'Polynesia'],
            ['nama_indonesia' => 'San Marino', 'nama_inggris' => 'San Marino', 'kode_iso' => 'SM', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Sao Tome dan Principe', 'nama_inggris' => 'Sao Tome and Principe', 'kode_iso' => 'ST', 'benua' => 'Africa', 'subbenua' => 'Middle Africa'],
            ['nama_indonesia' => 'Selandia Baru', 'nama_inggris' => 'New Zealand', 'kode_iso' => 'NZ', 'benua' => 'Oceania', 'subbenua' => 'Australia and New Zealand'],
            ['nama_indonesia' => 'Senegal', 'nama_inggris' => 'Senegal', 'kode_iso' => 'SN', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Serbia', 'nama_inggris' => 'Serbia', 'kode_iso' => 'RS', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Seychelles', 'nama_inggris' => 'Seychelles', 'kode_iso' => 'SC', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Sierra Leone', 'nama_inggris' => 'Sierra Leone', 'kode_iso' => 'SL', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Singapura', 'nama_inggris' => 'Singapore', 'kode_iso' => 'SG', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Siprus', 'nama_inggris' => 'Cyprus', 'kode_iso' => 'CY', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Slovenia', 'nama_inggris' => 'Slovenia', 'kode_iso' => 'SI', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Slowakia', 'nama_inggris' => 'Slovakia', 'kode_iso' => 'SK', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Solomon, Kepulauan', 'nama_inggris' => 'Solomon Islands', 'kode_iso' => 'SB', 'benua' => 'Oceania', 'subbenua' => 'Melanesia'],
            ['nama_indonesia' => 'Somalia', 'nama_inggris' => 'Somalia', 'kode_iso' => 'SO', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Spanyol', 'nama_inggris' => 'Spain', 'kode_iso' => 'ES', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Sri Lanka', 'nama_inggris' => 'Sri Lanka', 'kode_iso' => 'LK', 'benua' => 'Asia', 'subbenua' => 'Southern Asia'],
            ['nama_indonesia' => 'Sudan', 'nama_inggris' => 'Sudan', 'kode_iso' => 'SD', 'benua' => 'Africa', 'subbenua' => 'Northern Africa'],
            ['nama_indonesia' => 'Sudan Selatan', 'nama_inggris' => 'South Sudan', 'kode_iso' => 'SS', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Suriah', 'nama_inggris' => 'Syrian Arab Republic', 'kode_iso' => 'SY', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Suriname', 'nama_inggris' => 'Suriname', 'kode_iso' => 'SR', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Swedia', 'nama_inggris' => 'Sweden', 'kode_iso' => 'SE', 'benua' => 'Europe', 'subbenua' => 'Northern Europe'],
            ['nama_indonesia' => 'Swiss', 'nama_inggris' => 'Switzerland', 'kode_iso' => 'CH', 'benua' => 'Europe', 'subbenua' => 'Western Europe'],
            ['nama_indonesia' => 'Tajikistan', 'nama_inggris' => 'Tajikistan', 'kode_iso' => 'TJ', 'benua' => 'Asia', 'subbenua' => 'Central Asia'],
            ['nama_indonesia' => 'Tanjung Verde', 'nama_inggris' => 'Cabo Verde', 'kode_iso' => 'CV', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Tanzania', 'nama_inggris' => 'Tanzania', 'kode_iso' => 'TZ', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Thailand', 'nama_inggris' => 'Thailand', 'kode_iso' => 'TH', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Timor-Leste', 'nama_inggris' => 'Timor-Leste', 'kode_iso' => 'TL', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Tiongkok', 'nama_inggris' => 'China', 'kode_iso' => 'CN', 'benua' => 'Asia', 'subbenua' => 'Eastern Asia'],
            ['nama_indonesia' => 'Togo', 'nama_inggris' => 'Togo', 'kode_iso' => 'TG', 'benua' => 'Africa', 'subbenua' => 'Western Africa'],
            ['nama_indonesia' => 'Tonga', 'nama_inggris' => 'Tonga', 'kode_iso' => 'TO', 'benua' => 'Oceania', 'subbenua' => 'Polynesia'],
            ['nama_indonesia' => 'Trinidad dan Tobago', 'nama_inggris' => 'Trinidad and Tobago', 'kode_iso' => 'TT', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Tunisia', 'nama_inggris' => 'Tunisia', 'kode_iso' => 'TN', 'benua' => 'Africa', 'subbenua' => 'Northern Africa'],
            ['nama_indonesia' => 'Turki', 'nama_inggris' => 'Türkiye', 'kode_iso' => 'TR', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Turkmenistan', 'nama_inggris' => 'Turkmenistan', 'kode_iso' => 'TM', 'benua' => 'Asia', 'subbenua' => 'Central Asia'],
            ['nama_indonesia' => 'Tuvalu', 'nama_inggris' => 'Tuvalu', 'kode_iso' => 'TV', 'benua' => 'Oceania', 'subbenua' => 'Polynesia'],
            ['nama_indonesia' => 'Uganda', 'nama_inggris' => 'Uganda', 'kode_iso' => 'UG', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Ukraina', 'nama_inggris' => 'Ukraine', 'kode_iso' => 'UA', 'benua' => 'Europe', 'subbenua' => 'Eastern Europe'],
            ['nama_indonesia' => 'Uni Emirat Arab', 'nama_inggris' => 'United Arab Emirates', 'kode_iso' => 'AE', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Uruguay', 'nama_inggris' => 'Uruguay', 'kode_iso' => 'UY', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Uzbekistan', 'nama_inggris' => 'Uzbekistan', 'kode_iso' => 'UZ', 'benua' => 'Asia', 'subbenua' => 'Central Asia'],
            ['nama_indonesia' => 'Vanuatu', 'nama_inggris' => 'Vanuatu', 'kode_iso' => 'VU', 'benua' => 'Oceania', 'subbenua' => 'Melanesia'],
            ['nama_indonesia' => 'Vatikan', 'nama_inggris' => 'Holy See (Vatican City State)', 'kode_iso' => 'VA', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Venezuela', 'nama_inggris' => 'Venezuela', 'kode_iso' => 'VE', 'benua' => 'South America', 'subbenua' => 'South America'],
            ['nama_indonesia' => 'Vietnam', 'nama_inggris' => 'Viet Nam', 'kode_iso' => 'VN', 'benua' => 'Asia', 'subbenua' => 'South-eastern Asia'],
            ['nama_indonesia' => 'Yaman', 'nama_inggris' => 'Yemen', 'kode_iso' => 'YE', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Yordania', 'nama_inggris' => 'Jordan', 'kode_iso' => 'JO', 'benua' => 'Asia', 'subbenua' => 'Western Asia'],
            ['nama_indonesia' => 'Yunani', 'nama_inggris' => 'Greece', 'kode_iso' => 'GR', 'benua' => 'Europe', 'subbenua' => 'Southern Europe'],
            ['nama_indonesia' => 'Zambia', 'nama_inggris' => 'Zambia', 'kode_iso' => 'ZM', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Zimbabwe', 'nama_inggris' => 'Zimbabwe', 'kode_iso' => 'ZW', 'benua' => 'Africa', 'subbenua' => 'Eastern Africa'],
            ['nama_indonesia' => 'Hong Kong', 'nama_inggris' => 'Hong Kong, China', 'kode_iso' => 'HK', 'benua' => 'Asia', 'subbenua' => 'Eastern Asia'],
            ['nama_indonesia' => 'Makau', 'nama_inggris' => 'Macao, China', 'kode_iso' => 'MO', 'benua' => 'Asia', 'subbenua' => 'Eastern Asia'],
            ['nama_indonesia' => 'Taiwan', 'nama_inggris' => 'Taiwan, China', 'kode_iso' => 'TW', 'benua' => 'Asia', 'subbenua' => 'Eastern Asia'],
            ['nama_indonesia' => 'Puerto Riko', 'nama_inggris' => 'Puerto Rico', 'kode_iso' => 'PR', 'benua' => 'North America', 'subbenua' => 'Caribbean'],
            ['nama_indonesia' => 'Greenland', 'nama_inggris' => 'Greenland', 'kode_iso' => 'GL', 'benua' => 'North America', 'subbenua' => 'Northern America'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(
                ['kode_iso' => $country['kode_iso']],
                $country
            );
        }
    }
}
